name: Publish Docker

on:
  push:
  pull_request:

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build multi arch
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          tags: excalidraw/excalidraw:latest
      -
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        name: Push multi arch
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          tags: excalidraw/excalidraw:latest
          push: true
